arm_right_ft_sensor_robotiq:
  ros__parameters:
    type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    frame_id: robotiq_ft_frame_id
    sensor_name: robotiq_ft_sensor

adaptive_hqp:
  ros__parameters:
    type: elastoplastic::AdaptiveHQP
    target_joint_trajectory_topic: "/joints_target"
    robot_description_topic: "/robot_description"
    cmd_vel_topic: "/cmd_vel"
    ft_sensor_name: wrist_right_ft_sensor
    ft_invert_sign: false
    frames:
      map: odom
      # map: base_footprint
      base: base_footprint
      tool: arm_right_tool_link
      sensor: wrist_right_ft_sensor_link
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
    soft_limits:
      - 0.07
      - 0.07
      - 0.07
      - 0.07
      - 0.07
      - 0.07
      - 0.07
    kalman_filter:
      manipulator:
        position:
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
        velocity:
          - 1e0
          - 1e0
          - 1e0
          - 1e0
          - 1e0
          - 1e0
          - 1e0
    acceleration_limits_coeff: 1.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    mobile_base:
      enabled: true
      enable_z_rotation: false
      input_target_topic: "/target_cmd_vel"
      localization_topic: "/amcl_pose" # Unused
      odom: "/direct_laser_odometry/odom"
      use_command_interfaces: false
      command_interfaces:
      - "mobile_base_controller/linear/x"
      - "mobile_base_controller/linear/y"
      - "mobile_base_controller/angular/z"
      max_vel:
        linear: [0.5, 0.5]
        angular: 0.2
      max_acc_x: 0.5
      max_dec_x: 0.5
      max_acc_y: 0.5
      max_dec_y: 0.5
      max_acc_yaw: 0.5
      max_dec_yaw: 0.5
    wrench:
      deadband:
      - 2.0
      - 2.0
      filter_alfa: 0.2
      source: "ft_sensor"
      invert_torque: true # used only for if source==torque
      notch_filter:
        enable: true
        fc: 1.0
        Q: 1.0
    impedance:
      enable_axis: [true, true, true, false, false, false]
      inertia:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      k:
        - 10.0
        - 10.0
        - 10.0
        - 10.0
        - 10.0
        - 10.0
      d:
        - 100.0
        - 100.0
        - 100.0
        - 100.0
        - 100.0
        - 100.0
      z_max:   0.1 # [0.15, 0.15] # 0.1
      z_kmax:  0.098 # [0.14, 0.14] # 0.1
      z_start: 0.07  # [0.1, 0.1]   # 0.05
      logistic:
        max: 1.0
        slope: 10.0
        inflection: 0.5
      leak_coefficient: 0.02
      reset:
        time: 5.0
        threshold: 1e0
      plastic_restoration: false
    offset_force_window: 2.0 # seconds
    clik:
      alpha_gain: 1.0e6
      joint_task:
        kp: 1e1 # 1e1
        kv: 1e2 # 1e2
