arm_right_ft_sensor_robotiq:
  ros__parameters:
    type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    frame_id: robotiq_ft_frame_id
    sensor_name: robotiq_ft_sensor

adaptive_hqp:
  ros__parameters:
    type: elastoplastic::AdaptiveHQP
    use_threshold: 2 # 0 - only admitt, 1 - only track, 2 - mix
    target_joint_trajectory_topic: "/joints_target"
    robot_description_topic: "/robot_description"
    cmd_vel_topic: "/cmd_vel"
    # ft_sensor_name: wrist_right_ft_sensor
    ft_sensor_name: robotiq_ft_sensor
    ft_invert_sign: false
    gravity: [0.0, 0.0, -9.806]
    frames:
      map: map
      # map: base_footprint
      base: base_footprint
      # tool: arm_right_tool_link
      tool: robotiq_ft_frame_id
      sensor: robotiq_ft_frame_id  # for robot
      # sensor: wrist_right_ft_sensor_link  # on sim
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
    motor_torque_constants:  # NON CAMBIARE
      - 1.0 # 0.08  #-0.103 
      - 1.0 # 0.095  #-0.103 
      - 1.0 # 0.045  #-0.06  
      - 1.0 # 0.04  #-0.06  
      - 1.0 # 0.15  #-1.0   
      - 1.0 # 0.04  #-0.08  
      - 1.0 # 0.06  #-0.06  
    reduction_ratios:  # NON CAMBIARE
      - 1.0 # 121.0
      - 1.0 # 121.0
      - 1.0 # 101.0
      - 1.0 # 101.0
      - 1.0 # 101.0
      - 1.0 # 101.0
      - 1.0 # 101.0
    joints_static_friction:  # NON CAMBIARE
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
    joints_damping:  # NON CAMBIARE
      - 0.0 # 0.05
      - 0.0 # -1.0
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
      - 0.0 # 0.05
    soft_limits:
      - 0.0 # 0.07
      - 0.0 # 0.07
      - 0.0 # 0.07
      - 0.0 # 0.07
      - 0.0 # 0.07
      - 0.0 # 0.07
      - 0.0 # 0.07
    kalman_filter:
      manipulator:
        position:
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
          - 1e-1
        velocity:
          - 1e0
          - 1e0
          - 1e0
          - 1e0
          - 1e0
          - 1e0
          - 1e0
    acceleration_limits_coeff: 10.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    mobile_base:
      enabled: true
      virtual_inertia:
      - 10.0
      - 10.0
      - 50.0
      virtual_damping: 
      - 70.0
      - 70.0
      - 100.0
      enable_z_rotation: false
      input_target_topic: "/target_cmd_vel"
      localization_topic: "/amcl_pose" # Unused
      odom: "/direct_laser_odometry/odom"
      use_command_interfaces: false
      command_interfaces:
      - "mobile_base_controller/linear/x"
      - "mobile_base_controller/linear/y"
      - "mobile_base_controller/angular/z"
      max_vel:
        linear: [0.5, 0.5]
        angular: 0.1
      max_acc_x: 0.3
      max_dec_x: 0.3
      max_acc_y: 0.3
      max_dec_y: 0.3
      max_acc_yaw: 0.1
      max_dec_yaw: 0.1
    wrench:
      deadband:
      - 5.0
      - 5.0
      filter_alfa: 0.2
      source: "ft_sensor"
      invert_torque: true # used only for if source==torque
      notch_filter:
        enable: true
        fc: 1.0
        Q: 1.0
    impedance:
      wrench_threshold: 3.0
      enable_axis: [true, true, true, false, false, false]
      inertia:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      k:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      d:
        - 40.0
        - 40.0
        - 40.0
        - 40.0
        - 40.0
        - 40.0
      z_max:   0.1 # [0.15, 0.15] # 0.1
      z_kmax:  0.098 # [0.14, 0.14] # 0.1
      z_start: 0.07  # [0.1, 0.1]   # 0.05
      logistic:
        max: 1.0
        slope: 10.0
        inflection: 0.5
      leak_coefficient: 0.02
      reset:
        time: 5.0
        threshold: 1e0
      plastic_restoration: false
    offset_force_window: 2.0 # seconds
    clik:
      alpha_gain: 1.0e6
      joint_task:
        kp: 70.0 # 1e1
        # kv: 5.0 # 1e2
        kv: 50.0